using System;
using System.Collections.Generic;
using System.Text;

using System.Data;
using DAL.Info;

namespace DAL
{

    public class BLSETUPGROUPMETHODTREATMENT
    {
        DatabaseInfo dbInfo = null;
        public BLSETUPGROUPMETHODTREATMENT() { }
        public BLSETUPGROUPMETHODTREATMENT(DatabaseInfo dbInfo) { this.dbInfo = dbInfo; }

        public List<SETUPGROUPMETHODTREATMENT> GetSETUPGROUPMETHODTREATMENTByKey(int groupMethodID)
        {
            DASETUPGROUPMETHODTREATMENT DASETUPGROUPMETHODTREATMENT = (dbInfo == null ? new DASETUPGROUPMETHODTREATMENT() : new DASETUPGROUPMETHODTREATMENT(dbInfo));
            return DASETUPGROUPMETHODTREATMENT.GetSETUPGROUPMETHODTREATMENTByKey(groupMethodID);
        }

        public List<SETUPGROUPMETHODTREATMENT> GetSETUPGROUPMETHODTREATMENTByGroupMethodCode(string groupMethodCode)
        {
            DASETUPGROUPMETHODTREATMENT DASETUPGROUPMETHODTREATMENT = (dbInfo == null ? new DASETUPGROUPMETHODTREATMENT() : new DASETUPGROUPMETHODTREATMENT(dbInfo));
            return DASETUPGROUPMETHODTREATMENT.GetSETUPGROUPMETHODTREATMENTByGroupMethodCode(groupMethodCode);
        }

        public bool CheckDup(SETUPGROUPMETHODTREATMENT _SETUPGROUPMETHODTREATMENT)
        {
            DASETUPGROUPMETHODTREATMENT _DASETUPGROUPMETHODTREATMENT = (dbInfo == null ? new DASETUPGROUPMETHODTREATMENT() : new DASETUPGROUPMETHODTREATMENT(dbInfo));
            return _DASETUPGROUPMETHODTREATMENT.CheckDup(_SETUPGROUPMETHODTREATMENT);
        }

        public ReturnValue Insert(SETUPGROUPMETHODTREATMENT _SETUPGROUPMETHODTREATMENT)
        {
            DASETUPGROUPMETHODTREATMENT DASETUPGROUPMETHODTREATMENT = (dbInfo == null ? new DASETUPGROUPMETHODTREATMENT() : new DASETUPGROUPMETHODTREATMENT(dbInfo));
            return DASETUPGROUPMETHODTREATMENT.Insert(_SETUPGROUPMETHODTREATMENT);
        }

        public ReturnValue Update(SETUPGROUPMETHODTREATMENT _SETUPGROUPMETHODTREATMENT)
        {
            DASETUPGROUPMETHODTREATMENT DASETUPGROUPMETHODTREATMENT = (dbInfo == null ? new DASETUPGROUPMETHODTREATMENT() : new DASETUPGROUPMETHODTREATMENT(dbInfo));
            return DASETUPGROUPMETHODTREATMENT.Update(_SETUPGROUPMETHODTREATMENT);
        }

        public ReturnValue InActive(SETUPGROUPMETHODTREATMENT _SETUPGROUPMETHODTREATMENT)
        {
            DASETUPGROUPMETHODTREATMENT DASETUPGROUPMETHODTREATMENT = (dbInfo == null ? new DASETUPGROUPMETHODTREATMENT() : new DASETUPGROUPMETHODTREATMENT(dbInfo));
            return DASETUPGROUPMETHODTREATMENT.InActiveSETUPGROUPMETHODTREATMENT(_SETUPGROUPMETHODTREATMENT);
        }
        public SETUPGROUPMETHODTREATMENT GetSETUPGROUPMETHODTREATMENTByKey(SETUPGROUPMETHODTREATMENT _SETUPGROUPMETHODTREATMENT)
        {
            DASETUPGROUPMETHODTREATMENT DASETUPGROUPMETHODTREATMENT = (dbInfo == null ? new DASETUPGROUPMETHODTREATMENT() : new DASETUPGROUPMETHODTREATMENT(dbInfo));
            return DASETUPGROUPMETHODTREATMENT.GetSETUPGROUPMETHODTREATMENTByKey(_SETUPGROUPMETHODTREATMENT);
        }
        

    }
}
