using System;
using System.Collections.Generic;
using System.Text;

using System.Data;
using DAL.Info;

namespace DAL
{

    public class BLSETUPGROUPMETHODCLINIC
    {
        DatabaseInfo dbInfo = null;
        public BLSETUPGROUPMETHODCLINIC() { }
        public BLSETUPGROUPMETHODCLINIC(DatabaseInfo dbInfo) { this.dbInfo = dbInfo; }

        public List<SETUPGROUPMETHODCLINIC> GetSETUPGROUPMETHODCLINICByKey(int groupMethodID)
        {
            DASETUPGROUPMETHODCLINIC DASETUPGROUPMETHODCLINIC = (dbInfo == null ? new DASETUPGROUPMETHODCLINIC() : new DASETUPGROUPMETHODCLINIC(dbInfo));
            return DASETUPGROUPMETHODCLINIC.GetSETUPGROUPMETHODCLINICByKey(groupMethodID);
        }

        public List<SETUPGROUPMETHODCLINIC> GetSETUPGROUPMETHODCLINICByGroupMethodCode(string groupMethodCode)
        {
            DASETUPGROUPMETHODCLINIC DASETUPGROUPMETHODCLINIC = (dbInfo == null ? new DASETUPGROUPMETHODCLINIC() : new DASETUPGROUPMETHODCLINIC(dbInfo));
            return DASETUPGROUPMETHODCLINIC.GetSETUPGROUPMETHODCLINICByGroupMethodCode(groupMethodCode);
        }

        public bool CheckDup(SETUPGROUPMETHODCLINIC _SETUPGROUPMETHODCLINIC)
        {
            DASETUPGROUPMETHODCLINIC _DASETUPGROUPMETHODCLINIC = (dbInfo == null ? new DASETUPGROUPMETHODCLINIC() : new DASETUPGROUPMETHODCLINIC(dbInfo));
            return _DASETUPGROUPMETHODCLINIC.CheckDup(_SETUPGROUPMETHODCLINIC);
        }

        public ReturnValue Insert(SETUPGROUPMETHODCLINIC _SETUPGROUPMETHODCLINIC)
        {
            DASETUPGROUPMETHODCLINIC DASETUPGROUPMETHODCLINIC = (dbInfo == null ? new DASETUPGROUPMETHODCLINIC() : new DASETUPGROUPMETHODCLINIC(dbInfo));
            return DASETUPGROUPMETHODCLINIC.Insert(_SETUPGROUPMETHODCLINIC);
        }

        public ReturnValue Update(SETUPGROUPMETHODCLINIC _SETUPGROUPMETHODCLINIC)
        {
            DASETUPGROUPMETHODCLINIC DASETUPGROUPMETHODCLINIC = (dbInfo == null ? new DASETUPGROUPMETHODCLINIC() : new DASETUPGROUPMETHODCLINIC(dbInfo));
            return DASETUPGROUPMETHODCLINIC.Update(_SETUPGROUPMETHODCLINIC);
        }

        public ReturnValue InActive(SETUPGROUPMETHODCLINIC _SETUPGROUPMETHODCLINIC)
        {
            DASETUPGROUPMETHODCLINIC DASETUPGROUPMETHODCLINIC = (dbInfo == null ? new DASETUPGROUPMETHODCLINIC() : new DASETUPGROUPMETHODCLINIC(dbInfo));
            return DASETUPGROUPMETHODCLINIC.InActiveSETUPGROUPMETHODCLINIC(_SETUPGROUPMETHODCLINIC);
        }
        public SETUPGROUPMETHODCLINIC GetSETUPGROUPMETHODCLINICByKey(SETUPGROUPMETHODCLINIC _SETUPGROUPMETHODCLINIC)
        {
            DASETUPGROUPMETHODCLINIC DASETUPGROUPMETHODCLINIC = (dbInfo == null ? new DASETUPGROUPMETHODCLINIC() : new DASETUPGROUPMETHODCLINIC(dbInfo));
            return DASETUPGROUPMETHODCLINIC.GetSETUPGROUPMETHODCLINICByKey(_SETUPGROUPMETHODCLINIC);
        }
        

    }
}
