using System;
using System.Collections.Generic;
using System.Text;

using System.Data;
using DAL.Info;

namespace DAL
{

    public class BLSETUPGROUPMETHODMEDICINE
    {
        DatabaseInfo dbInfo = null;
        public BLSETUPGROUPMETHODMEDICINE() { }
        public BLSETUPGROUPMETHODMEDICINE(DatabaseInfo dbInfo) { this.dbInfo = dbInfo; }

        public List<SETUPGROUPMETHODMEDICINE> GetSETUPGROUPMETHODMEDICINEByKey(int groupMethodID)
        {
            DASETUPGROUPMETHODMEDICINE DASETUPGROUPMETHODMEDICINE = (dbInfo == null ? new DASETUPGROUPMETHODMEDICINE() : new DASETUPGROUPMETHODMEDICINE(dbInfo));
            return DASETUPGROUPMETHODMEDICINE.GetSETUPGROUPMETHODMEDICINEListByKey(groupMethodID);
        }

        public List<SETUPGROUPMETHODMEDICINE> GetSETUPGROUPMETHODMEDICINEByGroupMethodCode(string groupMethodCode)
        {
            DASETUPGROUPMETHODMEDICINE DASETUPGROUPMETHODMEDICINE = (dbInfo == null ? new DASETUPGROUPMETHODMEDICINE() : new DASETUPGROUPMETHODMEDICINE(dbInfo));
            return DASETUPGROUPMETHODMEDICINE.GetSETUPGROUPMETHODMEDICINEListByGroupMethodCode(groupMethodCode);
        }

        public bool CheckDup(SETUPGROUPMETHODMEDICINE _SETUPGROUPMETHODMEDICINE)
        {
            DASETUPGROUPMETHODMEDICINE _DASETUPGROUPMETHODMEDICINE = (dbInfo == null ? new DASETUPGROUPMETHODMEDICINE() : new DASETUPGROUPMETHODMEDICINE(dbInfo));
            return _DASETUPGROUPMETHODMEDICINE.CheckDup(_SETUPGROUPMETHODMEDICINE);
        }

        public ReturnValue Insert(SETUPGROUPMETHODMEDICINE _SETUPGROUPMETHODMEDICINE)
        {
            DASETUPGROUPMETHODMEDICINE _DASETUPGROUPMETHODMEDICINE = (dbInfo == null ? new DASETUPGROUPMETHODMEDICINE() : new DASETUPGROUPMETHODMEDICINE(dbInfo));
            return _DASETUPGROUPMETHODMEDICINE.Insert(_SETUPGROUPMETHODMEDICINE);
        }

        public ReturnValue Update(SETUPGROUPMETHODMEDICINE _SETUPGROUPMETHODMEDICINE)
        {
            DASETUPGROUPMETHODMEDICINE DASETUPGROUPMETHODMEDICINE = (dbInfo == null ? new DASETUPGROUPMETHODMEDICINE() : new DASETUPGROUPMETHODMEDICINE(dbInfo));
            return DASETUPGROUPMETHODMEDICINE.Update(_SETUPGROUPMETHODMEDICINE);
        }

        public ReturnValue InActive(SETUPGROUPMETHODMEDICINE _SETUPGROUPMETHODMEDICINE)
        {
            DASETUPGROUPMETHODMEDICINE DASETUPGROUPMETHODMEDICINE = (dbInfo == null ? new DASETUPGROUPMETHODMEDICINE() : new DASETUPGROUPMETHODMEDICINE(dbInfo));
            return DASETUPGROUPMETHODMEDICINE.InActiveSETUPGROUPMETHODMEDICINE(_SETUPGROUPMETHODMEDICINE);
        }
        public SETUPGROUPMETHODMEDICINE GetSETUPGROUPMETHODMEDICINEByKey(SETUPGROUPMETHODMEDICINE _SETUPGROUPMETHODMEDICINE)
        {
            DASETUPGROUPMETHODMEDICINE DASETUPGROUPMETHODMEDICINE = (dbInfo == null ? new DASETUPGROUPMETHODMEDICINE() : new DASETUPGROUPMETHODMEDICINE(dbInfo));
            return DASETUPGROUPMETHODMEDICINE.GetSETUPGROUPMETHODMEDICINEByKey(_SETUPGROUPMETHODMEDICINE);
        }
        

    }
}
